### ISSUE TITLE
Create logo for App and Visual ID

### ISSUE THREAD

**Issue by ViniciusDeep** [ViniciusDeep/Revill#7]
Create a logo, we have the provisional logo as you can see in Readme, but the idea is to create a logo, with a face of app, you can put this logo in place o R that in Readme and made a pull-request, or if you wanna a create a folder of Design and put logo.

Thanks a lot!

**Comment by bsoyka** [comment]
@ViniciusDeep I'd like to help out with this one. Is that okay?

**Comment by ViniciusDeep** [comment]
That's okay, I can assignee this Issue for you.

@bsoyka The color of App is  Background: #7B40FF Foreground: White

[Figma prototypes here](https://www.figma.com/file/8lTcWrH8EzPljSW9OVwIh8/Revill?node-id=0%3A1)

Here is a prototype
