### ISSUE TITLE
 Create Component at Search(Swift UI)

### ISSUE THREAD

**Issue by ViniciusDeep** [ViniciusDeep/Revill#9]
Create component at with Swift UI.

[Figma prototypes here](https://www.figma.com/file/8lTcWrH8EzPljSW9OVwIh8/Revill?node-id=0%3A1)
[Component](https://github.com/ViniciusDeep/Revill/blob/master/Revill/Revill/View/Feed/SearchView.swift)

Preview at Component
![Group 4 (1)](https://user-images.githubusercontent.com/32227073/65995378-cdfc2c00-e46b-11e9-804c-786c9fee9429.png)

And made a pull-request

**Comment by brunoorocha** [comment]
I would like to do this task
